on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 8
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
    - name: Build with Maven
      run: mvn -f app/pom.xml clean package

    - uses: actions/upload-artifact@v4
      with:
        name: verademo.war
        path: app/target/verademo.war
        
  pipeline_scan:
      needs: build
      runs-on: ubuntu-latest
      name: Veracode Pipeline Scan
      steps:
        - name: checkout repo
          uses: actions/checkout@v3

        - name: get archive
          uses: actions/download-artifact@v4
          with:
            name: verademo.war
            
        - name: pipeline-scan action step
          id: pipelien-scan
          uses: veracode/Veracode-pipeline-scan-action@esd-true
          with:
            vid: ${{ secrets.VID }}
            vkey: ${{ secrets.VKEY }}
            file: "verademo.war" 
            debug: 1
            fail_build: false
            
        - name: upload artifacts
          uses: actions/upload-artifact@v4
          with:
            name: Veracode Pipeline-Scan Results - ${{ github.run_number }}
            path: filtered_results.json 

  veracode-fix:
    runs-on: ubuntu-latest
    needs: pipeline_scan
    name: Veracode Fix
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: get flaw file
        uses: actions/download-artifact@v4
        with:
          name: Veracode Pipeline-Scan Results - ${{ github.run_number }}
          
      - name: Create fixes from static findings
        id: convert
        uses: sroy037/veracode-fix@main
        with:
          inputFile: filtered_results.json
          vid: ${{ secrets.VID }}
          vkey: ${{ secrets.VKEY }}
          source_base_path_1: "com/:app/src/main/java/com/"
          source_base_path_2: "WEB-INF:app/src/main/webapp/WEB-INF"
          language: java
          cwe: '117'
          prComment: false
          createPR: true
          fixType: batch
          debug: false
